import { expect, it, vi, afterEach } from 'vitest';
import { BrowserAnalyticsTransport, MAX_ANALYTICS_BODY_BYTES } from '../analytics-transport';
import { resolveConfig } from '../config';
import type { BrowserAnalyticsEvent } from '../types';
import { writeFileSync } from 'node:fs';

const event = (n: number, properties: Record<string, unknown> = {}): BrowserAnalyticsEvent => ({service_name:'app',event_id:n.toString(16).padStart(32,'0'),event_name:'goal',event_time:new Date().toISOString(),visitor_id:'1'.repeat(32),session_id:'2'.repeat(32),properties,page_url:'https://example.test/',page_path:'/',page_title:'',referrer:'',utm_source:'',utm_medium:'',utm_campaign:'',utm_term:'',utm_content:''});
const transport = () => new BrowserAnalyticsTransport(resolveConfig({apiKey:'key',endpoint:'https://tracekit.test'}));
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); });

 it('batches twenty events without blocking capture', async () => { vi.useFakeTimers(); const fetchMock=vi.fn(()=>Promise.resolve(new Response('',{status:202})));vi.stubGlobal('fetch',fetchMock);const t=transport();const sends=Array.from({length:20},(_,i)=>t.send(event(i)));expect(fetchMock).not.toHaveBeenCalled();await vi.advanceTimersByTimeAsync(100);await Promise.all(sends);expect(fetchMock).toHaveBeenCalledTimes(1);const body=JSON.parse((fetchMock.mock.calls as unknown as Array<[string,RequestInit]>)[0][1].body as string);expect(body.events).toHaveLength(20); });
 it('retries temporary failures with stable event identifiers', async () => { vi.useFakeTimers(); const fetchMock=vi.fn().mockResolvedValueOnce(new Response('',{status:503})).mockResolvedValueOnce(new Response('',{status:429})).mockResolvedValueOnce(new Response('',{status:200}));vi.stubGlobal('fetch',fetchMock);const t=transport();const p=t.send(event(7));await vi.advanceTimersByTimeAsync(100);await vi.advanceTimersByTimeAsync(1000);await p;expect(fetchMock).toHaveBeenCalledTimes(3);const ids=(fetchMock.mock.calls as unknown as Array<[string,RequestInit]>).map(c=>JSON.parse(c[1].body as string).events[0].event_id);expect(new Set(ids)).toEqual(new Set([event(7).event_id])); });
 it('honors bounded Retry-After and stops after four attempts', async () => { vi.useFakeTimers(); const timerSpy=vi.spyOn(globalThis,'setTimeout'); const fetchMock=vi.fn().mockResolvedValue(new Response('',{status:429,headers:{'Retry-After':'3'}}));vi.stubGlobal('fetch',fetchMock);const t=transport();const p=t.send(event(8));await vi.advanceTimersByTimeAsync(100);await vi.advanceTimersByTimeAsync(6000);await p;expect(fetchMock).toHaveBeenCalledTimes(4);const selectedDelays=timerSpy.mock.calls.map((call)=>call[1]).filter((delay):delay is number=>typeof delay==='number'&&delay>100);const maxDelay=Math.max(...selectedDelays);expect(maxDelay).toBe(2000);const path=process.env.PRIVATE_BETA_BROWSER_REPORT_FILE;if(path)writeFileSync(path,JSON.stringify({browser_max_retry_attempts:fetchMock.mock.calls.length,browser_max_retry_delay_ms:maxDelay})); timerSpy.mockRestore(); });
 it('does not retry permanent client failures', async () => { const fetchMock=vi.fn(()=>Promise.resolve(new Response('',{status:400})));vi.stubGlobal('fetch',fetchMock);const t=transport();expect(await t.send(event(9))).toBe(false);await new Promise(r=>setTimeout(r,120));expect(fetchMock).toHaveBeenCalledTimes(1); });
 it('bounds the queue and request body', async () => { vi.useFakeTimers();const fetchMock=vi.fn(()=>Promise.resolve(new Response('',{status:202})));vi.stubGlobal('fetch',fetchMock);const t=transport();const results=Array.from({length:101},(_,i)=>t.send(event(i,{padding:'x'.repeat(4000)})));expect(await results[100]).toBe(false);await vi.advanceTimersByTimeAsync(100);await Promise.all(results.slice(0,100));const payloads=(fetchMock.mock.calls as unknown as Array<[string,RequestInit]>).map(c=>JSON.parse(c[1].body as string));expect(payloads.some((payload)=>payload.events?.length < 20)).toBe(true);const ids=payloads.flatMap((payload)=>payload.events?.map((item:BrowserAnalyticsEvent)=>item.event_id) ?? [payload.event_id]);expect(ids).toHaveLength(100);expect(new Set(ids)).toEqual(new Set(Array.from({length:100},(_,i)=>event(i).event_id)));for(const c of fetchMock.mock.calls as unknown as Array<[string,RequestInit]>)expect(new TextEncoder().encode(c[1].body as string).byteLength).toBeLessThanOrEqual(MAX_ANALYTICS_BODY_BYTES); });
 it('uses the legacy envelope when one event cannot fit the batch wrapper', async () => { const fetchMock=vi.fn(()=>Promise.resolve(new Response('',{status:202})));vi.stubGlobal('fetch',fetchMock);const base=event(10,{padding:''});const baseBytes=new TextEncoder().encode(JSON.stringify(base)).byteLength;const large=event(10,{padding:'x'.repeat(MAX_ANALYTICS_BODY_BYTES-baseBytes-1)});const t=transport();await t.send(large);await new Promise(r=>setTimeout(r,120));expect(fetchMock).toHaveBeenCalledTimes(1);expect(JSON.parse((fetchMock.mock.calls as unknown as Array<[string,RequestInit]>)[0][1].body as string)).toHaveProperty('event_id'); });
